// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATmUr111MBKZWQJ5K1Vt2IP7tsbBOOKRo',
    appId: '1:196238899603:web:d0555ac980c0cd57059066',
    messagingSenderId: '196238899603',
    projectId: 'smartinterestx-6669a',
    authDomain: 'smartinterestx-6669a.firebaseapp.com',
    storageBucket: 'smartinterestx-6669a.firebasestorage.app',
    measurementId: 'G-MF946QVVGS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQtfJpnhKX3eZ4a4IYRn2pOR6kQidgyA',
    appId: '1:196238899603:ios:37b9049ff16059d4059066',
    messagingSenderId: '196238899603',
    projectId: 'smartinterestx-6669a',
    storageBucket: 'smartinterestx-6669a.firebasestorage.app',
    iosBundleId: 'com.example.smartInterestx',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALQtfJpnhKX3eZ4a4IYRn2pOR6kQidgyA',
    appId: '1:196238899603:ios:37b9049ff16059d4059066',
    messagingSenderId: '196238899603',
    projectId: 'smartinterestx-6669a',
    storageBucket: 'smartinterestx-6669a.firebasestorage.app',
    iosBundleId: 'com.example.smartInterestx',
  );
}
