// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPrM0yDmwePiTwrh6BCnGLWN7Cn8H32CQ',
    appId: '1:309634008254:web:f8cf56c5cc0a478263caef',
    messagingSenderId: '309634008254',
    projectId: 'my-backend-569d0',
    authDomain: 'my-backend-569d0.firebaseapp.com',
    storageBucket: 'my-backend-569d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtahbsJWlv_oCMTTtZUbc0JCi13uOLgzU',
    appId: '1:309634008254:android:cfbdea7428a1d81563caef',
    messagingSenderId: '309634008254',
    projectId: 'my-backend-569d0',
    storageBucket: 'my-backend-569d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAstqt0vex08TK-y-l9W0Lwi9OQzbwXrmA',
    appId: '1:309634008254:ios:cd4726c12f7f906463caef',
    messagingSenderId: '309634008254',
    projectId: 'my-backend-569d0',
    storageBucket: 'my-backend-569d0.firebasestorage.app',
    iosBundleId: 'com.example.myFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAstqt0vex08TK-y-l9W0Lwi9OQzbwXrmA',
    appId: '1:309634008254:ios:cd4726c12f7f906463caef',
    messagingSenderId: '309634008254',
    projectId: 'my-backend-569d0',
    storageBucket: 'my-backend-569d0.firebasestorage.app',
    iosBundleId: 'com.example.myFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPrM0yDmwePiTwrh6BCnGLWN7Cn8H32CQ',
    appId: '1:309634008254:web:90722c1b83b9394963caef',
    messagingSenderId: '309634008254',
    projectId: 'my-backend-569d0',
    authDomain: 'my-backend-569d0.firebaseapp.com',
    storageBucket: 'my-backend-569d0.firebasestorage.app',
  );
}
